const GROUPS = {
  Nature: [
    "Mountains",
    "Hills",
    "Lakes",
    "Rivers",
    "Waterfalls",
    "Forests",
    "National Parks",
    "Caves",
    "Viewpoints",
    "Sunrise Spots",
  ],

  Adventure: [
    "Trekking",
    "Hiking",
    "Rafting",
    "Kayaking",
    "Paragliding",
    "Bungee Jumping",
    "Zipline",
    "Rock Climbing",
    "Mountain Biking",
    "Camping",
    "Canyoning",
    "Heli Tour",
  ],

  Culture: [
    "Temples",
    "Monasteries",
    "Stupas",
    "Heritage Sites",
    "Museums",
    "Palaces",
    "Festivals",
    "Local Villages",
    "Traditions",
    "Crafts",
    "Architecture",
    "Food & Cuisine",
    "Cultural Shows",
  ],

  Spiritual: [
    "Meditation",
    "Yoga Retreats",
    "Pilgrimage",
    "Spiritual Centers",
    "Holy Sites",
    "Peace Pagodas",
    "Monastic Life",
  ],

  Wildlife: [
    "Safari",
    "Bird Watching",
    "Nature Walks",
    "Conservation Areas",
    "Eco Tours",
    "Jungle Walk",
    "Tiger Spotting",
    "Elephant Breeding Center",
  ],

  Relaxation: [
    "Resorts",
    "Spa & Wellness",
    "Hot Springs",
    "Lakeside Leisure",
    "Luxury Lodges",
    "Countryside Retreats",
    "Riverside Camping",
    "Sunset Views",
  ],

  Lifestyle: [
    "Homestays",
    "Cooking Classes",
    "Tea Gardens",
    "Local Markets",
    "Shopping",
    "Nightlife",
    "Community Tourism",
    "Volunteering",
  ],

  Themes: [
    "Family Travel",
    "Solo Travel",
    "Honeymoon",
    "Luxury Travel",
    "Budget Travel",
    "Offbeat Experiences",
    "Photography",
    "Festival Travel",
    "Eco Tourism",
    "Adventure Seekers",
    "Wellness Travel",
  ],
};

export default GROUPS;